services:
  app:
    container_name: groq-chatbot
    build:
      context: .
      dockerfile: Dockerfile
    image: groq-chatbot:latest
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:3000"
    restart: unless-stopped
    healthcheck:
      # Generic TCP check on port 3000 using Node (doesn't assume any HTTP route)
      test: ["CMD", "node", "-e", "require('net').connect(process.env.PORT||3000,'127.0.0.1').on('connect',()=>process.exit(0)).on('error',()=>process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

# Usage:
# 1) Ensure you have a .env file (copy from .env.example and fill GROQ_API_KEY)
# 2) Build:  docker compose build
# 3) Run:    docker compose up -d
# 4) Logs:   docker compose logs -f
# 5) Stop:   docker compose down
