services:
  app:
    container_name: groq-chatbot
    build:
      context: .
      dockerfile: Dockerfile
    image: groq-chatbot:latest
    env_file:
      - .env
    ports:
      - '${PORT:-3000}:3000'
    restart: unless-stopped
# Usage:
# 1) Ensure you have a .env file (copy from .env.example and fill GROQ_API_KEY)
# 2) Build:  docker compose build
# 3) Run:    docker compose up -d
# 4) Logs:   docker compose logs -f
# 5) Stop:   docker compose down
