version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: '22'
    image: groq-chatbot:latest
    env_file: .env
    ports:
      - '3000:3000'
    restart: unless-stopped
